### ISSUE TITLE
启动报错，说有两个bean

### ISSUE THREAD

**Issue by wm26hua** [yindz/jpush-spring-boot-starter#1]
`Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.apifan.framework.jpush.config.JPushProperties' available: expected single matching bean but found 2: JPushProperties,jpush-com.apifan.framework.jpush.config.JPushProperties
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:220)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1268)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 81 more`

**Comment by yindz** [comment]
抱歉，手抖多写了个@Comonent，新版1.0.2已修复
